services:
  - type: web
    name: jobaggregator
    runtime: docker
    repo: https://github.com/sobujinnovx-sys/jobaggregator.git
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    dockerArgs:
      CACHEBUST: "4"
    envVars:
      - key: APP_NAME
        value: JobAggregator
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromService:
          type: web
          name: jobaggregator
          property: host
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: LOG_CHANNEL
        value: stderr
      - key: CRON_TOKEN
        value: 7a777742817b19523acd04a8b7df9b8d
